### ISSUE TITLE
Play/Pause, Prev/Next, not working at all

### ISSUE THREAD

**Issue by Axarva** [ceuk/spotui#18] opened 2020-11-05 17:09 UTC
**Describe the bug**
When spotui is launched, it does run, show songs, navigation works as well
But when the song is played, it doesn't play
It looks as if no keys have been pressed.

**To Reproduce**
I do not have any ideas. As far as I can see, there are no logs, nothing. It just decides to stop working.

**Expected behavior**
Play/Pause, Next/Previous commands should work

**Desktop (please complete the following information):**
 - OS: Gentoo Linux (can reproduce this on both OpenRC and systemd)
 - Browser: Firefox
 - Version 0.1.17

**Comment by ceuk** [comment] 2020-11-05 17:30
hey, have you tried pressing `d` and making sure there is a device selected?

**Comment by Axarva** [comment] 2020-11-05 17:44
Yes, pressing `d` shows the devices menu, and I can select my device if I have launched spotify.
Also, spotui shows the song's progression and song being played if I play it through the spotify GUI.
However, it still doesn't work, standalone or even with the soptify application launched.

**Comment by ceuk** [comment] 2020-11-05 18:36
This app is designed to work in conjunction with a Spotify backend like [spotifyd](https://github.com/Spotifyd/spotifyd) it doesn't actually have the ability to play the music itself. 

Going to close this as it's technically not a bug if it's managing to control the GUI correctly, but if you have any other questions feel free to re-open.

**Closed as completed by ceuk** 2020-11-05 18:36 UTC

**Comment by Axarva** [comment] 2020-11-06 14:07
My apologies, seems like I wasn't clear. It **cannot control the GUI. It can reflect what the GUI is playing, but not control it's playback.**
I did try installing spotifyd as you suggest(hence the delay) and using the application, but it still couldn't function well. It appears more as a Spotify status bar instead of a program where I can actually control playback.

EDIT: Just as an experiment, I tried running it with superuser privileges but this didn't fix it as well, so I can confirm that this is not a permission issue.

**Comment by ceuk** [comment] 2020-11-06 16:10
Ah, I know what it might be, are you using a free account? You can't control playback on a free account as it's against Spotify's ToS

**Comment by Axarva** [comment] 2020-11-06 16:23
Yes, I am using a free account. I see, so that's the issue. Well, I guess I'll just have to use the GUI then. Thank you for the support. 
Maybe adding a little tip on the readme that playback won't work on free accounts will help avoid this issue for other users? :)

**Comment by ceuk** [comment] 2020-11-06 23:02
Done :)
